server:
  port: 8803
  
eureka:
  client:
    service-url:
      defaultZone: http://service-register-center1:8000/eureka, http://service-register-center2:8001/eureka

spring:
  application:
    name: auth-center
    
  datasource:
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/basicDB?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-wait: 10000
      max-active: 50
      test-on-borrow: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: 000000
  jpa:
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    
